# Generated by Django 4.1 on 2022-08-16 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycontent', '0002_answermodel_user_commentmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_comment', to='mycontent.answermodel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='mycontent.postmodel'),
        ),
    ]
