# Generated by Django 4.1 on 2022-08-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycontent', '0005_alter_commentmodel_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mycontent.postmodel'),
            preserve_default=False,
        ),
    ]
